### ISSUE TITLE
Duplicate key value error 

### ISSUE THREAD

**Issue by jvazquez-r7** [rapid7/metasploit-credential#87]
I'm experiencing some errors like that when using metasploit-credential on framework modules:

```
[-] Auxiliary failed: ActiveRecord::RecordNotUnique PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "unique_private_metasploit_credential_cores"
DETAIL:  Key (workspace_id, private_id)=(653, 9) already exists.
```

For example, I've experienced it (unique_private_metasploit_credential_cores) while validating this PR: https://github.com/rapid7/metasploit-framework/pull/4493 It happens when trying to create two **different** users with the **same** password. I think the duplication error is unexpected on a situation like that. But maybe there is some issue while using metasploit-credential. Please let me know if it's the case and I'll fix.

Another example, on https://github.com/rapid7/metasploit-framework/pull/4392, when running the module two times. The second one will generate a ```unique_public_metasploit_credential_cores``` violation. Also unexpected I think.

Thanks!

**Comment by todb-r7** [comment]
Let's see if we can't get some detailed repro steps here, that is easy to set up without exotic software, please. The repro steps on rapid7/metasploit-framework#4493 and rapid7/metasploit-framework#4392 are a little convoluted; some boiled down case (or better, a failing spec) would be ideal. Right now, I can't tell if the bug is due to not respecting a REALM for uniqueness, or merely rerunning with known creds causes the problem, or what.

**Comment by todb-r7** [comment]
Incidentally, @dmaloney-r7 , added @rapid7/framework-rapid7-committers to this repro, since it's open source and all. If that's not ok, let me know and I can yank.

**Comment by dmaloney-r7** [comment]
@jvazquez-r7 can you make sure your metasploit-credential is up to date?

**Comment by jvazquez-r7** [comment]
@dmaloney-r7 checking it today! Will update this pull request in a while!

**Comment by jvazquez-r7** [comment]
@dmaloney-r7 looks like I can trigger the error still:

```
msf auxiliary(manage_engine_dc_create_admin) > run

[+] 172.16.158.132:8020 - Created Administrator account with credentials msf2:password
[-] Auxiliary failed: ActiveRecord::RecordNotUnique PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "unique_private_metasploit_credential_cores"
DETAIL:  Key (workspace_id, private_id)=(654, 6) already exists.
: INSERT INTO "metasploit_credential_cores" ("created_at", "logins_count", "origin_id", "origin_type", "private_id", "public_id", "realm_id", "updated_at", "workspace_id") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"
[-] Call stack:
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176:in `get_last_result'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176:in `exec_cache'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:661:in `block in exec_query'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:659:in `exec_query'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:63:in `exec_insert'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:90:in `insert'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/relation.rb:66:in `insert'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/persistence.rb:367:in `create'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/timestamp.rb:58:in `create'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/callbacks.rb:268:in `block in create'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:403:in `_run__646245946632395940__create__4490362601557599606__callbacks'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_create_callbacks'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/callbacks.rb:268:in `create'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/persistence.rb:348:in `create_or_update'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/callbacks.rb:264:in `block in create_or_update'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:469:in `_run__646245946632395940__save__4490362601557599606__callbacks'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/callbacks.rb:264:in `create_or_update'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/persistence.rb:104:in `save!'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/validations.rb:56:in `save!'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/attribute_methods/dirty.rb:33:in `save!'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/transactions.rb:264:in `block in save!'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/transactions.rb:208:in `transaction'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/transactions.rb:264:in `save!'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/metasploit-credential-0.13.11/lib/metasploit/credential/creation.rb:181:in `block in create_credential_core'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/metasploit-credential-0.13.11/lib/metasploit/credential/creation.rb:533:in `retry_transaction'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/metasploit-credential-0.13.11/lib/metasploit/credential/creation.rb:173:in `create_credential_core'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/metasploit-credential-0.13.11/lib/metasploit/credential/creation.rb:145:in `create_credential'
[-]   /Users/jvazquez/Projects/Code/metasploit-framework/lib/msf/core/auxiliary/report.rb:25:in `create_credential'
[-]   /Users/jvazquez/Projects/Code/metasploit-framework/modules/auxiliary/admin/http/manage_engine_dc_create_admin.rb:89:in `run'
[*] Auxiliary module execution completed
```

I'm working with the metasploit-credential gem required by framework in rapid7 master: metasploit-credential (0.13.11)

Am I forgetting something?

In order to reproduce I'm using the modules/auxiliary/admin/http/manage_engine_dc_create_admin.rb module. Steps:

- [ ] Comment the next code (so you don't need to install the vulnerable app):

```ruby
=begin
    salt = Time.now.to_i.to_s
    password_encoded = Rex::Text.encode_base64([Rex::Text.md5(datastore['PASSWORD'] + salt)].pack('H*'))

    res = send_request_cgi({
      'uri'      => normalize_uri(target_uri.path, "/servlets/DCPluginServelet"),
      'method'   =>'GET',
      'vars_get' => {
        'action'      => 'addPlugInUser',
        'role'        => 'DCAdmin',
        'userName'    => datastore['USERNAME'],
        'email'       => datastore['EMAIL'],
        'phNumber'    => Rex::Text.rand_text_numeric(6),
        'password'    => password_encoded,
        'salt'        => salt,
        'createdtime' => salt
      }
    })

    # Yes, "sucess" is really mispelt, as is "Servelet" ... !
    unless res && res.code == 200 && res.body && res.body.to_s =~ /sucess/
      print_error("#{peer} - Administrator account creation failed")
    end
=end

```

The code in run will just do:

```
    print_good("#{peer} - Created Administrator account with credentials #{datastore['USERNAME']}:#{datastore['PASSWORD']}")
    service_data = {
      address: rhost,
      port: rport,
      service_name: (ssl ? 'https' : 'http'),
      protocol: 'tcp',
      workspace_id: myworkspace_id
    }
    credential_data = {
      origin_type: :service,
      module_fullname: self.fullname,
      private_type: :password,
      private_data: datastore['PASSWORD'],
      username: datastore['USERNAME']
    }

    credential_data.merge!(service_data)
    credential_core = create_credential(credential_data)
    login_data = {
      core: credential_core,
      access_level: 'Administrator',
      status: Metasploit::Model::Login::Status::UNTRIED
    }
    login_data.merge!(service_data)
    create_credential_login(login_data)
```

- [ ] Create a new workspace ```workspace -a duplicate_key```
- [ ] Set any valid IP as RHOST and ```run```:

```
msf auxiliary(manage_engine_dc_create_admin) > workspace -a test_duplicate
[*] Added workspace: test_duplicate
msf auxiliary(manage_engine_dc_create_admin) > use auxiliary/admin/http/manage_engine_dc_create_admin
msf auxiliary(manage_engine_dc_create_admin) > run

[+] 172.16.158.131:8020 - Created Administrator account with credentials msf:password
[*] Auxiliary module execution completed
```

- [ ] Check which the cred has been created successfully:

```
msf auxiliary(manage_engine_dc_create_admin) > creds
Credentials
===========

host            service          public  private   realm  private_type
----            -------          ------  -------   -----  ------------
172.16.158.131  8020/tcp (http)  msf     password         Password
```

- [ ] set a new USERNAME, for example ```msf2``` (keep the others options!)

- [ ] run again, it's raising an exception here:

```
msf auxiliary(manage_engine_dc_create_admin) > run

[+] 172.16.158.131:8020 - Created Administrator account with credentials msf2:password
[-] Auxiliary failed: ActiveRecord::RecordNotUnique PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "unique_private_metasploit_credential_cores"
DETAIL:  Key (workspace_id, private_id)=(655, 6) already exists.
: INSERT INTO "metasploit_credential_cores" ("created_at", "logins_count", "origin_id", "origin_type", "private_id", "public_id", "realm_id", "updated_at", "workspace_id") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"
[-] Call stack:
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176:in `get_last_result'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176:in `exec_cache'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:661:in `block in exec_query'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:659:in `exec_query'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:63:in `exec_insert'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:90:in `insert'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/relation.rb:66:in `insert'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/persistence.rb:367:in `create'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/timestamp.rb:58:in `create'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/callbacks.rb:268:in `block in create'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:403:in `_run__4207866742761322871__create__2425299280420848472__callbacks'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_create_callbacks'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/callbacks.rb:268:in `create'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/persistence.rb:348:in `create_or_update'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/callbacks.rb:264:in `block in create_or_update'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:469:in `_run__4207866742761322871__save__2425299280420848472__callbacks'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/callbacks.rb:264:in `create_or_update'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/persistence.rb:104:in `save!'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/validations.rb:56:in `save!'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/attribute_methods/dirty.rb:33:in `save!'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/transactions.rb:264:in `block in save!'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/transactions.rb:208:in `transaction'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/transactions.rb:264:in `save!'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/metasploit-credential-0.13.11/lib/metasploit/credential/creation.rb:181:in `block in create_credential_core'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/metasploit-credential-0.13.11/lib/metasploit/credential/creation.rb:533:in `retry_transaction'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/metasploit-credential-0.13.11/lib/metasploit/credential/creation.rb:173:in `create_credential_core'
[-]   /Users/jvazquez/.rvm/gems/ruby-2.1.4@metasploit-framework/gems/metasploit-credential-0.13.11/lib/metasploit/credential/creation.rb:145:in `create_credential'
[-]   /Users/jvazquez/Projects/Code/metasploit-framework/lib/msf/core/auxiliary/report.rb:25:in `create_credential'
[-]   /Users/jvazquez/Projects/Code/metasploit-framework/modules/auxiliary/admin/http/manage_engine_dc_create_admin.rb:89:in `run'
[*] Auxiliary module execution completed
```

(Check how it is using metasploit-credential-0.13.11) ^^^

**Comment by jhart-r7** [comment]
https://github.com/rapid7/metasploit-framework/issues/4561 may also be related

**Comment by jvazquez-r7** [comment]
This one has been solved by just resetting the DB, looks like I'm dirty :\ and I kept it corrupted? It had been a long time since I reseted really. Anyway:

```rake db::drop
rake db::create
rake db::migrate
```
solved the issue :) Thanks @dmaloney-r7 for the feedback and assistance! :)

```
msf > use auxiliary/admin/http/manage_engine_dc_create_admin
msf auxiliary(manage_engine_dc_create_admin) > set rhost 172.16.158.131
rhost => 172.16.158.131
msf auxiliary(manage_engine_dc_create_admin) > run

[+] 172.16.158.131:8020 - Created Administrator account with credentials msf:password
s[*] Auxiliary module execution completed
msf auxiliary(manage_engine_dc_create_admin) > creds
Credentials
===========

host            service          public  private   realm  private_type
----            -------          ------  -------   -----  ------------
172.16.158.131  8020/tcp (http)  msf     password         Password

msf auxiliary(manage_engine_dc_create_admin) > set username msf2
username => msf2
msf auxiliary(manage_engine_dc_create_admin) > run

[+] 172.16.158.131:8020 - Created Administrator account with credentials msf2:password
[*] Auxiliary module execution completed
msf auxiliary(manage_engine_dc_create_admin) > creds
Credentials
===========

host            service          public  private   realm  private_type
----            -------          ------  -------   -----  ------------
172.16.158.131  8020/tcp (http)  msf2    password         Password
172.16.158.131  8020/tcp (http)  msf     password         Password
```
